/* GENERADO por scripts/importar-renders.mjs — no editar a mano */

/** clave: linea|modelo|acabado(lam|esm|inox)|color, valor: ruta dentro de public/ */
export const RENDERS: Record<string, string> = {
  "LEEDER|COLGANTE|lam|gris": "renders/leeder-colgante-lam-gris.webp",
  "LEEDER|COLGANTE|lam|negro": "renders/leeder-colgante-lam-negro.webp",
  "LEEDER|COLGANTE|lam|blanco": "renders/leeder-colgante-lam-blanco.webp",
  "LEEDER|COLGANTE|lam|grafito-nocturno": "renders/leeder-colgante-lam-grafito-nocturno.webp",
  "LEEDER|COLGANTE|lam|inox-satin": "renders/leeder-colgante-lam-inox-satin.webp",
  "LEEDER|COLGANTE|lam|nogal-grafito": "renders/leeder-colgante-lam-nogal-grafito.webp",
  "LEEDER|COLGANTE|lam|ambar-wood": "renders/leeder-colgante-lam-ambar-wood.webp",
  "LEEDER|ESTANDAR170|lam|gris": "renders/leeder-estandar170-lam-gris.webp",
  "LEEDER|ESTANDAR170|lam|negro": "renders/leeder-estandar170-lam-negro.webp",
  "LEEDER|ESTANDAR170|lam|blanco": "renders/leeder-estandar170-lam-blanco.webp",
  "LEEDER|ESTANDAR170|lam|grafito-nocturno": "renders/leeder-estandar170-lam-grafito-nocturno.webp",
  "LEEDER|ESTANDAR170|lam|inox-satin": "renders/leeder-estandar170-lam-inox-satin.webp",
  "LEEDER|ESTANDAR170|lam|nogal-grafito": "renders/leeder-estandar170-lam-nogal-grafito.webp",
  "LEEDER|ESTANDAR170|lam|ambar-wood": "renders/leeder-estandar170-lam-ambar-wood.webp",
  "LEEDER|ESTANDAR|lam|gris": "renders/leeder-estandar-lam-gris.webp",
  "LEEDER|ESTANDAR|lam|negro": "renders/leeder-estandar-lam-negro.webp",
  "LEEDER|ESTANDAR|lam|blanco": "renders/leeder-estandar-lam-blanco.webp",
  "LEEDER|ESTANDAR|lam|grafito-nocturno": "renders/leeder-estandar-lam-grafito-nocturno.webp",
  "LEEDER|ESTANDAR|lam|inox-satin": "renders/leeder-estandar-lam-inox-satin.webp",
  "LEEDER|ESTANDAR|lam|nogal-grafito": "renders/leeder-estandar-lam-nogal-grafito.webp",
  "LEEDER|ESTANDAR|lam|ambar-wood": "renders/leeder-estandar-lam-ambar-wood.webp",
  "LEEDER|KIDS|lam|gris": "renders/leeder-kids-lam-gris.webp",
  "LEEDER|KIDS|lam|negro": "renders/leeder-kids-lam-negro.webp",
  "LEEDER|KIDS|lam|blanco": "renders/leeder-kids-lam-blanco.webp",
  "LEEDER|KIDS|lam|grafito-nocturno": "renders/leeder-kids-lam-grafito-nocturno.webp",
  "LEEDER|KIDS|lam|inox-satin": "renders/leeder-kids-lam-inox-satin.webp",
  "LEEDER|KIDS|lam|nogal-grafito": "renders/leeder-kids-lam-nogal-grafito.webp",
  "LEEDER|KIDS|lam|ambar-wood": "renders/leeder-kids-lam-ambar-wood.webp",
  "LEEDER|__ORINAL|lam|gris": "renders/leeder-orinal-lam-gris.webp",
  "LEEDER|__ORINAL|lam|negro": "renders/leeder-orinal-lam-negro.webp",
  "LEEDER|__ORINAL|lam|blanco": "renders/leeder-orinal-lam-blanco.webp",
  "LEEDER|__ORINAL|lam|grafito-nocturno": "renders/leeder-orinal-lam-grafito-nocturno.webp",
  "LEEDER|__ORINAL|lam|inox-satin": "renders/leeder-orinal-lam-inox-satin.webp",
  "LEEDER|__ORINAL|lam|nogal-grafito": "renders/leeder-orinal-lam-nogal-grafito.webp",
  "LEEDER|__ORINAL|lam|ambar-wood": "renders/leeder-orinal-lam-ambar-wood.webp",
  "LEEDER|REFORZADO170|lam|gris": "renders/leeder-reforzado170-lam-gris.webp",
  "LEEDER|REFORZADO170|lam|negro": "renders/leeder-reforzado170-lam-negro.webp",
  "LEEDER|REFORZADO170|lam|blanco": "renders/leeder-reforzado170-lam-blanco.webp",
  "LEEDER|REFORZADO170|lam|grafito-nocturno": "renders/leeder-reforzado170-lam-grafito-nocturno.webp",
  "LEEDER|REFORZADO170|lam|inox-satin": "renders/leeder-reforzado170-lam-inox-satin.webp",
  "LEEDER|REFORZADO170|lam|nogal-grafito": "renders/leeder-reforzado170-lam-nogal-grafito.webp",
  "LEEDER|REFORZADO170|lam|ambar-wood": "renders/leeder-reforzado170-lam-ambar-wood.webp",
  "LEEDER|REFORZADO|lam|gris": "renders/leeder-reforzado-lam-gris.webp",
  "LEEDER|REFORZADO|lam|negro": "renders/leeder-reforzado-lam-negro.webp",
  "LEEDER|REFORZADO|lam|blanco": "renders/leeder-reforzado-lam-blanco.webp",
  "LEEDER|REFORZADO|lam|grafito-nocturno": "renders/leeder-reforzado-lam-grafito-nocturno.webp",
  "LEEDER|REFORZADO|lam|inox-satin": "renders/leeder-reforzado-lam-inox-satin.webp",
  "LEEDER|REFORZADO|lam|nogal-grafito": "renders/leeder-reforzado-lam-nogal-grafito.webp",
  "LEEDER|REFORZADO|lam|ambar-wood": "renders/leeder-reforzado-lam-ambar-wood.webp",
  "LEEDER|__REGADERA|lam|gris": "renders/leeder-regadera-lam-gris.webp",
  "LEEDER|__REGADERA|lam|negro": "renders/leeder-regadera-lam-negro.webp",
  "LEEDER|__REGADERA|lam|blanco": "renders/leeder-regadera-lam-blanco.webp",
  "LEEDER|__REGADERA|lam|grafito-nocturno": "renders/leeder-regadera-lam-grafito-nocturno.webp",
  "LEEDER|__REGADERA|lam|inox-satin": "renders/leeder-regadera-lam-inox-satin.webp",
  "LEEDER|__REGADERA|lam|nogal-grafito": "renders/leeder-regadera-lam-nogal-grafito.webp",
  "LEEDER|__REGADERA|lam|ambar-wood": "renders/leeder-regadera-lam-ambar-wood.webp",
  "LEEDER|SCUDO|lam|gris": "renders/leeder-scudo-lam-gris.webp",
  "LEEDER|SCUDO|lam|negro": "renders/leeder-scudo-lam-negro.webp",
  "LEEDER|SCUDO|lam|blanco": "renders/leeder-scudo-lam-blanco.webp",
  "LEEDER|SCUDO|lam|grafito-nocturno": "renders/leeder-scudo-lam-grafito-nocturno.webp",
  "LEEDER|SCUDO|lam|inox-satin": "renders/leeder-scudo-lam-inox-satin.webp",
  "LEEDER|SCUDO|lam|nogal-grafito": "renders/leeder-scudo-lam-nogal-grafito.webp",
  "LEEDER|SCUDO|lam|ambar-wood": "renders/leeder-scudo-lam-ambar-wood.webp",
  "SUPERIOR|COLGANTE|lam|blanco-antiguo": "renders/superior-colgante-lam-blanco-antiguo.webp",
  "SUPERIOR|COLGANTE|lam|negro": "renders/superior-colgante-lam-negro.webp",
  "SUPERIOR|COLGANTE|lam|inox-satin": "renders/superior-colgante-lam-inox-satin.webp",
  "SUPERIOR|COLGANTE|lam|holly": "renders/superior-colgante-lam-holly.webp",
  "SUPERIOR|COLGANTE|lam|lapis": "renders/superior-colgante-lam-lapis.webp",
  "SUPERIOR|COLGANTE|lam|nogal-grafito": "renders/superior-colgante-lam-nogal-grafito.webp",
  "SUPERIOR|COLGANTE|lam|ambar-wood": "renders/superior-colgante-lam-ambar-wood.webp",
  "SUPERIOR|COLGANTE|lam|gris": "renders/superior-colgante-lam-gris.webp",
  "SUPERIOR|COLGANTE|lam|blanco": "renders/superior-colgante-lam-blanco.webp",
  "SUPERIOR|COLGANTE|lam|grafito-nocturno": "renders/superior-colgante-lam-grafito-nocturno.webp",
  "SUPERIOR|COLGANTE|esm|esmalte-blanco": "renders/superior-colgante-esm-esmalte-blanco.webp",
  "SUPERIOR|COLGANTE|esm|esmalte-beige": "renders/superior-colgante-esm-esmalte-beige.webp",
  "SUPERIOR|COLGANTE|esm|esmaltada-antigrafiti": "renders/superior-colgante-esm-esmaltada-antigrafiti.webp",
  "SUPERIOR|COLGANTE|inox|acero-inoxidable": "renders/superior-colgante-inox-acero-inoxidable.webp",
  "SUPERIOR|ESTANDAR170|lam|gris": "renders/superior-estandar170-lam-gris.webp",
  "SUPERIOR|ESTANDAR170|lam|blanco-antiguo": "renders/superior-estandar170-lam-blanco-antiguo.webp",
  "SUPERIOR|ESTANDAR170|lam|blanco": "renders/superior-estandar170-lam-blanco.webp",
  "SUPERIOR|ESTANDAR170|lam|grafito-nocturno": "renders/superior-estandar170-lam-grafito-nocturno.webp",
  "SUPERIOR|ESTANDAR170|lam|inox-satin": "renders/superior-estandar170-lam-inox-satin.webp",
  "SUPERIOR|ESTANDAR170|lam|holly": "renders/superior-estandar170-lam-holly.webp",
  "SUPERIOR|ESTANDAR170|lam|lapis": "renders/superior-estandar170-lam-lapis.webp",
  "SUPERIOR|ESTANDAR170|lam|negro": "renders/superior-estandar170-lam-negro.webp",
  "SUPERIOR|ESTANDAR170|lam|nogal-grafito": "renders/superior-estandar170-lam-nogal-grafito.webp",
  "SUPERIOR|ESTANDAR170|lam|ambar-wood": "renders/superior-estandar170-lam-ambar-wood.webp",
  "SUPERIOR|ESTANDAR170|inox|acero-inoxidable": "renders/superior-estandar170-inox-acero-inoxidable.webp",
  "SUPERIOR|ESTANDAR170|esm|esmalte-beige": "renders/superior-estandar170-esm-esmalte-beige.webp",
  "SUPERIOR|ESTANDAR170|esm|esmalte-blanco": "renders/superior-estandar170-esm-esmalte-blanco.webp",
  "SUPERIOR|ESTANDAR170|esm|esmaltada-antigrafiti": "renders/superior-estandar170-esm-esmaltada-antigrafiti.webp",
  "SUPERIOR|ESTANDAR|lam|gris": "renders/superior-estandar-lam-gris.webp",
  "SUPERIOR|ESTANDAR|lam|blanco-antiguo": "renders/superior-estandar-lam-blanco-antiguo.webp",
  "SUPERIOR|ESTANDAR|lam|blanco": "renders/superior-estandar-lam-blanco.webp",
  "SUPERIOR|ESTANDAR|lam|grafito-nocturno": "renders/superior-estandar-lam-grafito-nocturno.webp",
  "SUPERIOR|ESTANDAR|lam|inox-satin": "renders/superior-estandar-lam-inox-satin.webp",
  "SUPERIOR|ESTANDAR|lam|holly": "renders/superior-estandar-lam-holly.webp",
  "SUPERIOR|ESTANDAR|lam|lapis": "renders/superior-estandar-lam-lapis.webp",
  "SUPERIOR|ESTANDAR|lam|negro": "renders/superior-estandar-lam-negro.webp",
  "SUPERIOR|ESTANDAR|lam|nogal-grafito": "renders/superior-estandar-lam-nogal-grafito.webp",
  "SUPERIOR|ESTANDAR|lam|ambar-wood": "renders/superior-estandar-lam-ambar-wood.webp",
  "SUPERIOR|ESTANDAR|esm|esmalte-beige": "renders/superior-estandar-esm-esmalte-beige.webp",
  "SUPERIOR|ESTANDAR|esm|esmalte-blanco": "renders/superior-estandar-esm-esmalte-blanco.webp",
  "SUPERIOR|ESTANDAR|esm|esmaltada-antigrafiti": "renders/superior-estandar-esm-esmaltada-antigrafiti.webp",
  "SUPERIOR|ESTANDAR|inox|acero-inoxidable": "renders/superior-estandar-inox-acero-inoxidable.webp",
  "SUPERIOR|__ORINAL|lam|gris": "renders/superior-orinal-lam-gris.webp",
  "SUPERIOR|__ORINAL|lam|blanco-antiguo": "renders/superior-orinal-lam-blanco-antiguo.webp",
  "SUPERIOR|__ORINAL|lam|blanco": "renders/superior-orinal-lam-blanco.webp",
  "SUPERIOR|__ORINAL|lam|grafito-nocturno": "renders/superior-orinal-lam-grafito-nocturno.webp",
  "SUPERIOR|__ORINAL|lam|inox-satin": "renders/superior-orinal-lam-inox-satin.webp",
  "SUPERIOR|__ORINAL|lam|holly": "renders/superior-orinal-lam-holly.webp",
  "SUPERIOR|__ORINAL|lam|lapis": "renders/superior-orinal-lam-lapis.webp",
  "SUPERIOR|__ORINAL|lam|negro": "renders/superior-orinal-lam-negro.webp",
  "SUPERIOR|__ORINAL|lam|nogal-grafito": "renders/superior-orinal-lam-nogal-grafito.webp",
  "SUPERIOR|__ORINAL|lam|ambar-wood": "renders/superior-orinal-lam-ambar-wood.webp",
  "SUPERIOR|__ORINAL|esm|esmalte-beige": "renders/superior-orinal-esm-esmalte-beige.webp",
  "SUPERIOR|__ORINAL|esm|esmalte-blanco": "renders/superior-orinal-esm-esmalte-blanco.webp",
  "SUPERIOR|__ORINAL|esm|esmaltada-antigrafiti": "renders/superior-orinal-esm-esmaltada-antigrafiti.webp",
  "SUPERIOR|__ORINAL|inox|acero-inoxidable": "renders/superior-orinal-inox-acero-inoxidable.webp",
  "SUPERIOR|REFORZADO170|lam|blanco-antiguo": "renders/superior-reforzado170-lam-blanco-antiguo.webp",
  "SUPERIOR|REFORZADO170|lam|blanco": "renders/superior-reforzado170-lam-blanco.webp",
  "SUPERIOR|REFORZADO170|lam|inox-satin": "renders/superior-reforzado170-lam-inox-satin.webp",
  "SUPERIOR|REFORZADO170|lam|holly": "renders/superior-reforzado170-lam-holly.webp",
  "SUPERIOR|REFORZADO170|lam|lapis": "renders/superior-reforzado170-lam-lapis.webp",
  "SUPERIOR|REFORZADO170|lam|negro": "renders/superior-reforzado170-lam-negro.webp",
  "SUPERIOR|REFORZADO170|lam|nogal-grafito": "renders/superior-reforzado170-lam-nogal-grafito.webp",
  "SUPERIOR|REFORZADO170|lam|ambar-wood": "renders/superior-reforzado170-lam-ambar-wood.webp",
  "SUPERIOR|REFORZADO170|lam|gris": "renders/superior-reforzado170-lam-gris.webp",
  "SUPERIOR|REFORZADO170|lam|grafito-nocturno": "renders/superior-reforzado170-lam-grafito-nocturno.webp",
  "SUPERIOR|REFORZADO170|esm|esmaltada-antigrafiti": "renders/superior-reforzado170-esm-esmaltada-antigrafiti.webp",
  "SUPERIOR|REFORZADO170|esm|esmalte-beige": "renders/superior-reforzado170-esm-esmalte-beige.webp",
  "SUPERIOR|REFORZADO170|esm|esmalte-blanco": "renders/superior-reforzado170-esm-esmalte-blanco.webp",
  "SUPERIOR|REFORZADO170|inox|acero-inoxidable": "renders/superior-reforzado170-inox-acero-inoxidable.webp",
  "SUPERIOR|REFORZADO|lam|gris": "renders/superior-reforzado-lam-gris.webp",
  "SUPERIOR|REFORZADO|lam|blanco-antiguo": "renders/superior-reforzado-lam-blanco-antiguo.webp",
  "SUPERIOR|REFORZADO|lam|blanco": "renders/superior-reforzado-lam-blanco.webp",
  "SUPERIOR|REFORZADO|lam|grafito-nocturno": "renders/superior-reforzado-lam-grafito-nocturno.webp",
  "SUPERIOR|REFORZADO|lam|inox-satin": "renders/superior-reforzado-lam-inox-satin.webp",
  "SUPERIOR|REFORZADO|lam|holly": "renders/superior-reforzado-lam-holly.webp",
  "SUPERIOR|REFORZADO|lam|lapis": "renders/superior-reforzado-lam-lapis.webp",
  "SUPERIOR|REFORZADO|lam|negro": "renders/superior-reforzado-lam-negro.webp",
  "SUPERIOR|REFORZADO|lam|nogal-grafito": "renders/superior-reforzado-lam-nogal-grafito.webp",
  "SUPERIOR|REFORZADO|lam|ambar-wood": "renders/superior-reforzado-lam-ambar-wood.webp",
  "SUPERIOR|REFORZADO|esm|esmaltada-antigrafiti": "renders/superior-reforzado-esm-esmaltada-antigrafiti.webp",
  "SUPERIOR|REFORZADO|esm|esmalte-beige": "renders/superior-reforzado-esm-esmalte-beige.webp",
  "SUPERIOR|REFORZADO|esm|esmalte-blanco": "renders/superior-reforzado-esm-esmalte-blanco.webp",
  "SUPERIOR|REFORZADO|inox|acero-inoxidable": "renders/superior-reforzado-inox-acero-inoxidable.webp",
  "SUPERIOR|__REGADERA|lam|gris": "renders/superior-regadera-lam-gris.webp",
  "SUPERIOR|__REGADERA|lam|blanco-antiguo": "renders/superior-regadera-lam-blanco-antiguo.webp",
  "SUPERIOR|__REGADERA|lam|blanco": "renders/superior-regadera-lam-blanco.webp",
  "SUPERIOR|__REGADERA|lam|grafito-nocturno": "renders/superior-regadera-lam-grafito-nocturno.webp",
  "SUPERIOR|__REGADERA|lam|inox-satin": "renders/superior-regadera-lam-inox-satin.webp",
  "SUPERIOR|__REGADERA|lam|holly": "renders/superior-regadera-lam-holly.webp",
  "SUPERIOR|__REGADERA|lam|lapis": "renders/superior-regadera-lam-lapis.webp",
  "SUPERIOR|__REGADERA|lam|negro": "renders/superior-regadera-lam-negro.webp",
  "SUPERIOR|__REGADERA|lam|nogal-grafito": "renders/superior-regadera-lam-nogal-grafito.webp",
  "SUPERIOR|__REGADERA|lam|ambar-wood": "renders/superior-regadera-lam-ambar-wood.webp",
  "SUPERIOR|__REGADERA|inox|acero-inoxidable": "renders/superior-regadera-inox-acero-inoxidable.webp",
  "SUPERIOR|__REGADERA|esm|esmalte-beige": "renders/superior-regadera-esm-esmalte-beige.webp",
  "SUPERIOR|__REGADERA|esm|esmalte-blanco": "renders/superior-regadera-esm-esmalte-blanco.webp",
  "SUPERIOR|__REGADERA|esm|esmaltada-antigrafiti": "renders/superior-regadera-esm-esmaltada-antigrafiti.webp",
  "TOUCHLESS|TL_S3|lam|inox-satin": "renders/touchless-tls3-lam-inox-satin.webp",
  "TOUCHLESS|TL_S3|lam|gris": "renders/touchless-tls3-lam-gris.webp",
  "TOUCHLESS|TL_S3|lam|negro": "renders/touchless-tls3-lam-negro.webp",
  "TOUCHLESS|TL_S3|lam|blanco": "renders/touchless-tls3-lam-blanco.webp",
  "TOUCHLESS|TL_S3|lam|grafito-nocturno": "renders/touchless-tls3-lam-grafito-nocturno.webp",
  "TOUCHLESS|TL_S3|lam|nogal-grafito": "renders/touchless-tls3-lam-nogal-grafito.webp",
  "TOUCHLESS|TL_S3|lam|ambar-wood": "renders/touchless-tls3-lam-ambar-wood.webp"
}

/**
 * Colores que vinieron en los renders de Superior 2.0 y que NO están en el
 * catálogo del Constructor, así que hoy no se pueden elegir. Quedan indexados
 * por si mercadeo confirma que entran a la lista.
 */
export const COLORES_FUERA_DE_CATALOGO = [
  "blanco-antiguo",
  "esmalte-beige",
  "esmalte-blanco",
  "holly",
  "lapis"
]
